name: AceLounge
version: 3.0
author: Delta203
depend: [ViaVersion]

main: de.servermanager.delta203.plugin.ServerManager

commands:
  stop:
       permission: be.op
  icanhasbukkit:
  help:
  ?:
  coins:
  diamonds:
  rules:
  regeln:
  terms:
  apply:
  bewerben:
  yt:
  youtuber:
  discord:
  logindatas:
  changepassword:
  luck:
  ping:
  trololol:
  vanish:
       permission: ab.ban
  console:
       permission: be.op